---
title: "Research Proposal Template Using [RMarkdown](http://rmarkdown.rstudio.com) and [Zotero](www.zotero.org)"
author: "Bailey Albinger"
date: "Spring 2015"
output: html_document
bibliography: ResearchProposal1.bib
---

# Introduction:

Anixiety disorder and alcoholism coicide due to the pressures and stress relivants of both of the factors together. A number of studies have shown that individuals with anxiety disorders have a higher than expected prevalence of alcohol abuse.This connection between alcohol dependence and states of anxiety may show the important problems in understanding the etiology of and for preventing and treating both disorders.

Drinking alcohol has been shown in experiments that it in fact lowers indiduals levels of anxiety at the moment. Considering it is a temporary treatment, people turn to alcohol more and more, which in turn turns it into a dependence of alcohol[bibb_alcohol_1986.

The onset of anxiety disorders tend to precede the onset of alcohol abuse. The role of alcohol proves to put a weaker role of strength to get passed anxieties and panic disorders. It has been shown that alcohol dependence also has a big factor with phobias such as agoraphobia. Anxieties grow more serios due to alcohol consumption and not facing mental illnesses. 

The present studies examine individuals in rehabs and mental hospitals. These experiments link the cordiual effects that anxiety and alcohol have together. The goal is to provide data to explain why the disorders rely on eachother and what could be done as a precaution.

# Methods:

## Sample

The sample from the first study examines a population of admitted alcoholics living in a institutionalized facility. They take alcohol screening tests  and consumption levels to test the clinical results of alcoholism and to see what effect anxiety has on the alcohol consumption. There were 102 people in the sample.

## Procedure

Each individual answered questionaires based on there experiences and self-report  symptoms scales were used to validate the clinical ratings.

## Measures

Of the 102 alcoholics admitted too an alcoholismtreatment one third were clinically rated with a socil phobia and a disabling agoraphobia. Another third was had anxiety disorders but they were less disabling.

## Implications:

While the individuals promised to be honest and truthful, there was no way to ensure that the tests and questionaires were honest. The alcohol abuse issues can stem from other mental illnesses or experiences other than anxiety disorders.

# References
According to @{bibb_alcohol_1986
This source {mullaney_alcohol_1979
The reviewed Source {stravynski_clinical_1986
Says {george_alcoholism_1990
States {stockwell_alcohol_1984
